local M = {}
---@class Palette
---@field mode "dark"|"light"
---@field accent string
---@field selection string
---@field muted string
---@field background string
---@field dark_background string
---@field darker_background string
---@field lighter_background string
---@field foreground string
---@field dark_foreground string
---@field light_foreground string
---@field bright_foreground string
---@field red string
---@field yellow string
---@field orange string
---@field green string
---@field cyan string
---@field blue string
---@field magenta string
---@field brown string
---@field bright_red string
---@field bright_yellow string
---@field bright_green string
---@field bright_cyan string
---@field bright_blue string
---@field bright_magenta string

---Setup all highlight groups
---@param p Palette Configuration
---@return table<string, vim.api.keyset.highlight>
function M.highlights_for(p)
	local highlights = {
		Added = { fg = p.green },
		Boolean = { fg = p.orange, bold = true },
		Changed = { fg = p.yellow },
		Character = { fg = p.green },
		CmpItemAbbr = { fg = p.foreground },
		CmpItemAbbrMatch = { fg = p.accent, bold = true },
		CmpItemAbbrMatchFuzzy = { fg = p.accent, bold = true },
		CmpItemKind = { fg = p.cyan },
		CmpItemMenu = { fg = p.dark_foreground, italic = true },
		ColorColumn = { bg = p.selection },
		Comment = { fg = p.dark_foreground, italic = true },
		Conceal = { fg = p.muted },
		Conditional = { fg = p.magenta, bold = true },
		Constant = { fg = p.orange },
		CurSearch = { fg = p.background, bg = p.orange, bold = true },
		Cursor = { fg = p.background, bg = p.bright_foreground },
		CursorColumn = { bg = p.selection },
		CursorLine = { bg = p.selection },
		CursorLineNr = { fg = p.accent, bold = true },
		Debug = { fg = p.red },
		Define = { fg = p.cyan },
		Delimiter = { fg = p.foreground },
		DiagnosticError = { fg = p.red },
		DiagnosticHint = { fg = p.cyan },
		DiagnosticInfo = { fg = p.blue },
		DiagnosticOk = { fg = p.green },
		DiagnosticSignError = { fg = p.red },
		DiagnosticSignHint = { fg = p.cyan },
		DiagnosticSignInfo = { fg = p.blue },
		DiagnosticSignWarn = { fg = p.yellow },
		DiagnosticUnderlineError = { sp = p.red, undercurl = true },
		DiagnosticUnderlineHint = { sp = p.cyan, undercurl = true },
		DiagnosticUnderlineInfo = { sp = p.blue, undercurl = true },
		DiagnosticUnderlineWarn = { sp = p.yellow, undercurl = true },
		DiagnosticVirtualTextError = { fg = p.red, italic = true },
		DiagnosticVirtualTextHint = { fg = p.cyan, italic = true },
		DiagnosticVirtualTextInfo = { fg = p.blue, italic = true },
		DiagnosticVirtualTextOk = { fg = p.green, italic = true },
		DiagnosticVirtualTextWarn = { fg = p.yellow, italic = true },
		DiagnosticWarn = { fg = p.yellow },
		DiffAdd = { fg = p.green, bg = p.dark_background },
		DiffChange = { fg = p.yellow, bg = p.dark_background },
		DiffDelete = { fg = p.red, bg = p.dark_background },
		DiffText = { fg = p.bright_foreground, bg = p.selection, bold = true },
		Directory = { fg = p.blue, bold = true },
		EndOfBuffer = { fg = p.dark_background },
		Error = { fg = p.red, bold = true },
		ErrorMsg = { fg = p.red, bold = true },
		Exception = { fg = p.red, bold = true },
		Float = { fg = p.orange },
		FloatBorder = { fg = p.muted, bg = p.lighter_background },
		FloatTitle = { fg = p.accent, bg = p.lighter_background, bold = true },
		FoldColumn = { fg = p.dark_foreground, bg = p.background },
		Folded = { fg = p.dark_foreground, bg = p.dark_background, italic = true },
		Function = { fg = p.blue, bold = true },
		GitSignsAdd = { fg = p.green },
		GitSignsChange = { fg = p.yellow },
		GitSignsDelete = { fg = p.red },
		HealthError = { fg = p.red, bold = true },
		HealthSuccess = { fg = p.green, bold = true },
		HealthWarning = { fg = p.yellow, bold = true },
		Identifier = { fg = p.foreground },
		IncSearch = { fg = p.background, bg = p.orange, bold = true },
		Include = { fg = p.cyan },
		Keyword = { fg = p.magenta, bold = true },
		Label = { fg = p.cyan },
		LineNr = { fg = p.dark_foreground },
		LspCodeLens = { fg = p.dark_foreground, italic = true },
		LspCodeLensSeparator = { fg = p.muted },
		LspInlayHint = { fg = p.dark_foreground, bg = p.dark_background, italic = true },
		LspReferenceRead = { bg = p.selection },
		LspReferenceText = { bg = p.selection },
		LspReferenceWrite = { bg = p.selection, bold = true },
		LspSignatureActiveParameter = { fg = p.bright_foreground, bg = p.selection, bold = true },
		Macro = { fg = p.cyan },
		MatchParen = { fg = p.bright_foreground, bg = p.muted, bold = true },
		ModeMsg = { fg = p.foreground, bold = true },
		MoreMsg = { fg = p.cyan, bold = true },
		MsgArea = { fg = p.foreground, bg = p.background },
		NonText = { fg = p.dark_foreground },
		Normal = { fg = p.foreground, bg = p.background },
		NormalFloat = { fg = p.foreground, bg = p.lighter_background },
		NormalNC = { fg = p.foreground, bg = p.dark_background },
		Number = { fg = p.orange },
		Operator = { fg = p.cyan },
		Pmenu = { fg = p.foreground, bg = p.lighter_background },
		PmenuSbar = { bg = p.selection },
		PmenuSel = { fg = p.bright_foreground, bg = p.selection, bold = true },
		PmenuThumb = { bg = p.muted },
		PreCondit = { fg = p.cyan },
		PreProc = { fg = p.cyan },
		Question = { fg = p.green, bold = true },
		Removed = { fg = p.red },
		Repeat = { fg = p.magenta, bold = true },
		Search = { fg = p.background, bg = p.yellow, bold = true },
		SignColumn = { fg = p.dark_foreground, bg = p.background },
		Special = { fg = p.cyan },
		SpecialChar = { fg = p.orange },
		SpecialKey = { fg = p.dark_foreground },
		SpellBad = { sp = p.red, undercurl = true },
		SpellCap = { sp = p.yellow, undercurl = true },
		SpellLocal = { sp = p.cyan, undercurl = true },
		SpellRare = { sp = p.magenta, undercurl = true },
		Statement = { fg = p.magenta, bold = true },
		StatusLine = { fg = p.foreground, bg = p.lighter_background },
		StatusLineNC = { fg = p.dark_foreground, bg = p.dark_background },
		StorageClass = { fg = p.yellow, bold = true },
		String = { fg = p.green },
		Structure = { fg = p.yellow, bold = true },
		Substitute = { fg = p.background, bg = p.magenta, bold = true },
		TabLine = { fg = p.dark_foreground, bg = p.dark_background },
		TabLineFill = { bg = p.dark_background },
		TabLineSel = { fg = p.bright_foreground, bg = p.background, bold = true },
		Tag = { fg = p.blue },
		TelescopeBorder = { fg = p.muted, bg = p.lighter_background },
		TelescopeMatching = { fg = p.blue, bold = true },
		TelescopeNormal = { fg = p.foreground, bg = p.lighter_background },
		TelescopePromptBorder = { fg = p.selection, bg = p.selection },
		TelescopePromptNormal = { fg = p.foreground, bg = p.selection },
		TelescopePromptPrefix = { fg = p.accent, bg = p.selection },
		TelescopePromptTitle = { fg = p.background, bg = p.accent, bold = true },
		TelescopeResultsDiffAdd = { fg = p.green },
		TelescopeResultsDiffChange = { fg = p.yellow },
		TelescopeResultsDiffDelete = { fg = p.red },
		TelescopeSelection = { fg = p.bright_foreground, bg = p.selection, bold = true },
		TelescopeTitle = { fg = p.accent, bg = p.lighter_background, bold = true },
		Title = { fg = p.accent, bold = true },
		Todo = { fg = p.background, bg = p.yellow, bold = true },
		Type = { fg = p.yellow, bold = true },
		Typedef = { fg = p.yellow, bold = true },
		Underlined = { fg = p.blue, underline = true },
		VertSplit = { fg = p.muted },
		Visual = { bg = p.selection },
		VisualNOS = { bg = p.selection },
		WarningMsg = { fg = p.yellow, bold = true },
		WhichKey = { fg = p.accent, bold = true },
		WhichKeyDesc = { fg = p.foreground },
		WhichKeyFloat = { bg = p.lighter_background },
		WhichKeyGroup = { fg = p.cyan },
		WhichKeySeparator = { fg = p.muted },
		WhichKeyValue = { fg = p.dark_foreground, italic = true },
		Whitespace = { fg = p.dark_foreground },
		WildMenu = { fg = p.bright_foreground, bg = p.selection, bold = true },
		WinBar = { fg = p.foreground, bg = p.background, bold = true },
		WinBarNC = { fg = p.dark_foreground, bg = p.background },
		WinSeparator = { fg = p.muted },
		["@boolean"] = { link = "Boolean" },
		["@character"] = { link = "Character" },
		["@comment"] = { link = "Comment" },
		["@constant"] = { link = "Constant" },
		["@constant.builtin"] = { fg = p.orange, italic = true },
		["@constructor"] = { fg = p.yellow, bold = true },
		["@diff.delta"] = { fg = p.yellow },
		["@diff.minus"] = { fg = p.red },
		["@diff.plus"] = { fg = p.green },
		["@field"] = { fg = p.blue },
		["@float"] = { link = "Float" },
		["@function"] = { link = "Function" },
		["@function.builtin"] = { fg = p.cyan, bold = true },
		["@function.call"] = { fg = p.blue },
		["@function.method"] = { fg = p.blue, bold = true },
		["@function.method.call"] = { fg = p.blue },
		["@keyword"] = { link = "Keyword" },
		["@keyword.conditional"] = { fg = p.magenta, bold = true },
		["@keyword.function"] = { fg = p.magenta, bold = true },
		["@keyword.import"] = { fg = p.cyan, bold = true },
		["@keyword.operator"] = { fg = p.cyan, bold = true },
		["@keyword.repeat"] = { fg = p.magenta, bold = true },
		["@keyword.return"] = { fg = p.magenta, bold = true },
		["@markup.heading"] = { fg = p.accent, bold = true },
		["@markup.italic"] = { fg = p.foreground, italic = true },
		["@markup.link"] = { fg = p.blue, underline = true },
		["@markup.raw"] = { fg = p.green },
		["@markup.strong"] = { fg = p.bright_foreground, bold = true },
		["@number"] = { link = "Number" },
		["@operator"] = { link = "Operator" },
		["@property"] = { fg = p.blue },
		["@punctuation.bracket"] = { fg = p.foreground },
		["@punctuation.delimiter"] = { fg = p.muted },
		["@punctuation.special"] = { fg = p.cyan },
		["@string"] = { link = "String" },
		["@string.documentation"] = { fg = p.green, italic = true },
		["@string.escape"] = { fg = p.orange, bold = true },
		["@string.special"] = { fg = p.cyan },
		["@tag"] = { fg = p.blue, bold = true },
		["@tag.attribute"] = { fg = p.yellow },
		["@tag.delimiter"] = { fg = p.muted },
		["@type"] = { link = "Type" },
		["@type.builtin"] = { fg = p.yellow, italic = true },
		["@type.definition"] = { fg = p.yellow, bold = true },
		["@variable"] = { fg = p.foreground },
		["@variable.builtin"] = { fg = p.red, italic = true },
		["@variable.member"] = { fg = p.blue },
		["@variable.parameter"] = { fg = p.foreground, italic = true },
		markdownBold = { fg = p.bright_foreground, bold = true },
		markdownCode = { fg = p.green },
		markdownCodeBlock = { fg = p.green },
		markdownH1 = { fg = p.accent, bold = true },
		markdownH2 = { fg = p.blue, bold = true },
		markdownH3 = { fg = p.cyan, bold = true },
		markdownH4 = { fg = p.green, bold = true },
		markdownItalic = { fg = p.foreground, italic = true },
		markdownLinkText = { fg = p.blue, underline = true },
	}
	return highlights
end

return M
