local M = {}

---Setup all highlight groups
---@param gui GuiPalette|nil
---@param ansi AnsiPalette
---@return table<string, vim.api.keyset.highlight>
function M.highlights_for(gui, ansi)
	gui = gui or {}

	local highlights = {
		Added = { fg = gui.green, ctermfg = ansi.green },
		Boolean = { fg = gui.orange, ctermfg = ansi.yellow, bold = true },
		Changed = { fg = gui.yellow, ctermfg = ansi.yellow },
		Character = { fg = gui.green, ctermfg = ansi.green },
		CmpItemAbbr = { fg = gui.foreground, ctermfg = ansi.foreground },
		CmpItemAbbrMatch = { fg = gui.accent, bold = true },
		CmpItemAbbrMatchFuzzy = { fg = gui.accent, bold = true },
		CmpItemKind = { fg = gui.cyan, ctermfg = ansi.cyan },
		CmpItemMenu = { fg = gui.light_foreground, ctermfg = ansi.foreground, italic = true },
		ColorColumn = { bg = gui.selection, ctermbg = ansi.selection },
		Comment = { fg = gui.light_foreground, ctermfg = ansi.foreground, italic = true },
		Conceal = { fg = gui.muted, ctermfg = ansi.selection },
		Conditional = { fg = gui.magenta, ctermfg = ansi.magenta, bold = true },
		Constant = { fg = gui.orange, ctermfg = ansi.yellow },
		CurSearch = { fg = gui.orange, ctermfg = ansi.yellow, bold = true, reverse = true },
		Cursor = {
			fg = gui.background,
			ctermfg = ansi.background,
			bg = gui.bright_foreground,
			ctermbg = ansi.bright_foreground,
		},
		CursorColumn = { bg = gui.selection, ctermbg = ansi.selection },
		CursorLine = { bg = gui.selection, ctermbg = ansi.selection },
		CursorLineNr = { fg = gui.accent, bold = true },
		Debug = { fg = gui.red, ctermfg = ansi.red },
		Define = { fg = gui.cyan, ctermfg = ansi.cyan },
		Delimiter = { fg = gui.foreground, ctermfg = ansi.foreground },
		DiagnosticError = { fg = gui.red, ctermfg = ansi.red },
		DiagnosticHint = { fg = gui.cyan, ctermfg = ansi.cyan },
		DiagnosticInfo = { fg = gui.blue, ctermfg = ansi.blue },
		DiagnosticOk = { fg = gui.green, ctermfg = ansi.green },
		DiagnosticSignError = { fg = gui.red, ctermfg = ansi.red },
		DiagnosticSignHint = { fg = gui.cyan, ctermfg = ansi.cyan },
		DiagnosticSignInfo = { fg = gui.blue, ctermfg = ansi.blue },
		DiagnosticSignWarn = { fg = gui.yellow, ctermfg = ansi.yellow },
		DiagnosticUnderlineError = { sp = gui.red, undercurl = true },
		DiagnosticUnderlineHint = { sp = gui.cyan, undercurl = true },
		DiagnosticUnderlineInfo = { sp = gui.blue, undercurl = true },
		DiagnosticUnderlineWarn = { sp = gui.yellow, undercurl = true },
		DiagnosticVirtualTextError = { fg = gui.red, ctermfg = ansi.red, italic = true },
		DiagnosticVirtualTextHint = { fg = gui.cyan, ctermfg = ansi.cyan, italic = true },
		DiagnosticVirtualTextInfo = { fg = gui.blue, ctermfg = ansi.blue, italic = true },
		DiagnosticVirtualTextOk = { fg = gui.green, ctermfg = ansi.green, italic = true },
		DiagnosticVirtualTextWarn = { fg = gui.yellow, ctermfg = ansi.yellow, italic = true },
		DiagnosticWarn = { fg = gui.yellow, ctermfg = ansi.yellow },
		DiffAdd = {
			fg = gui.green,
			ctermfg = ansi.green,
			bg = gui.dark_background,
			ctermbg = ansi.background,
		},
		DiffChange = {
			fg = gui.yellow,
			ctermfg = ansi.yellow,
			bg = gui.dark_background,
			ctermbg = ansi.background,
		},
		DiffDelete = {
			fg = gui.red,
			ctermfg = ansi.red,
			bg = gui.dark_background,
			ctermbg = ansi.background,
		},
		DiffText = {
			fg = gui.bright_foreground,
			ctermfg = ansi.bright_foreground,
			bg = gui.selection,
			ctermbg = ansi.selection,
			bold = true,
		},
		Directory = { fg = gui.blue, ctermfg = ansi.blue, bold = true },
		EndOfBuffer = { fg = gui.dark_background, ctermfg = ansi.background },
		Error = { fg = gui.red, ctermfg = ansi.red, bold = true },
		ErrorMsg = { fg = gui.red, ctermfg = ansi.red, bold = true },
		Exception = { fg = gui.red, ctermfg = ansi.red, bold = true },
		Float = { fg = gui.orange, ctermfg = ansi.yellow },
		FloatBorder = {
			fg = gui.muted,
			ctermfg = ansi.selection,
			bg = gui.lighter_background,
			ctermbg = ansi.background,
		},
		FloatTitle = {
			fg = gui.accent,
			bg = gui.lighter_background,
			ctermbg = ansi.background,
			bold = true,
		},
		FoldColumn = {
			fg = gui.light_foreground,
			ctermfg = ansi.foreground,
			bg = gui.background,
			ctermbg = ansi.background,
		},
		Folded = {
			fg = gui.light_foreground,
			ctermfg = ansi.foreground,
			bg = gui.dark_background,
			ctermbg = ansi.background,
			italic = true,
		},
		Function = { fg = gui.blue, ctermfg = ansi.blue, bold = true },
		GitSignsAdd = { fg = gui.green, ctermfg = ansi.green },
		GitSignsChange = { fg = gui.yellow, ctermfg = ansi.yellow },
		GitSignsDelete = { fg = gui.red, ctermfg = ansi.red },
		HealthError = { fg = gui.red, ctermfg = ansi.red, bold = true },
		HealthSuccess = { fg = gui.green, ctermfg = ansi.green, bold = true },
		HealthWarning = { fg = gui.yellow, ctermfg = ansi.yellow, bold = true },
		Identifier = { fg = gui.foreground, ctermfg = ansi.foreground },
		IncSearch = { fg = gui.orange, ctermfg = ansi.yellow, bold = true, reverse = true },
		Include = { fg = gui.cyan, ctermfg = ansi.cyan },
		Keyword = { fg = gui.magenta, ctermfg = ansi.magenta, bold = true },
		Label = { fg = gui.cyan, ctermfg = ansi.cyan },
		LineNr = { fg = gui.light_foreground, ctermfg = ansi.foreground },
		LspCodeLens = { fg = gui.light_foreground, ctermfg = ansi.foreground, italic = true },
		LspCodeLensSeparator = { fg = gui.muted, ctermfg = ansi.selection },
		LspInlayHint = {
			fg = gui.light_foreground,
			ctermfg = ansi.foreground,
			bg = gui.dark_background,
			ctermbg = ansi.background,
			italic = true,
		},
		LspReferenceRead = { bg = gui.selection, ctermbg = ansi.selection },
		LspReferenceText = { bg = gui.selection, ctermbg = ansi.selection },
		LspReferenceWrite = { bg = gui.selection, ctermbg = ansi.selection, bold = true },
		LspSignatureActiveParameter = {
			fg = gui.bright_foreground,
			ctermfg = ansi.bright_foreground,
			bg = gui.selection,
			ctermbg = ansi.selection,
			bold = true,
		},
		Macro = { fg = gui.cyan, ctermfg = ansi.cyan },
		MatchParen = {
			fg = gui.bright_foreground,
			ctermfg = ansi.bright_foreground,
			bg = gui.muted,
			ctermbg = ansi.selection,
			bold = true,
		},
		ModeMsg = { fg = gui.foreground, ctermfg = ansi.foreground, bold = true },
		MoreMsg = { fg = gui.cyan, ctermfg = ansi.cyan, bold = true },
		MsgArea = {
			fg = gui.foreground,
			ctermfg = ansi.foreground,
			bg = gui.background,
			ctermbg = ansi.background,
		},
		NonText = { fg = gui.light_foreground, ctermfg = ansi.foreground },
		Normal = {
			fg = gui.foreground,
			ctermfg = ansi.foreground,
			bg = gui.background,
			ctermbg = ansi.background,
		},
		NormalFloat = {
			fg = gui.foreground,
			ctermfg = ansi.foreground,
			bg = gui.lighter_background,
			ctermbg = ansi.background,
		},
		NormalNC = {
			fg = gui.foreground,
			ctermfg = ansi.foreground,
			bg = gui.dark_background,
			ctermbg = ansi.background,
		},
		Number = { fg = gui.orange, ctermfg = ansi.yellow },
		Operator = { fg = gui.cyan, ctermfg = ansi.cyan },
		Pmenu = {
			fg = gui.foreground,
			ctermfg = ansi.foreground,
			bg = gui.lighter_background,
			ctermbg = ansi.background,
		},
		PmenuSbar = { bg = gui.selection, ctermbg = ansi.selection },
		PmenuSel = {
			fg = gui.bright_foreground,
			ctermfg = ansi.bright_foreground,
			bg = gui.selection,
			ctermbg = ansi.selection,
			bold = true,
		},
		PmenuThumb = { bg = gui.muted, ctermbg = ansi.selection },
		PreCondit = { fg = gui.cyan, ctermfg = ansi.cyan },
		PreProc = { fg = gui.cyan, ctermfg = ansi.cyan },
		Question = { fg = gui.green, ctermfg = ansi.green, bold = true },
		Removed = { fg = gui.red, ctermfg = ansi.red },
		Repeat = { fg = gui.magenta, ctermfg = ansi.magenta, bold = true },
		Search = {
			fg = gui.background,
			ctermfg = ansi.background,
			bg = gui.yellow,
			ctermbg = ansi.yellow,
			bold = true,
		},
		SignColumn = { fg = gui.light_foreground, ctermfg = ansi.foreground },
		Special = { fg = gui.cyan, ctermfg = ansi.cyan },
		SpecialChar = { fg = gui.orange, ctermfg = ansi.yellow },
		SpecialKey = { fg = gui.light_foreground, ctermfg = ansi.foreground },
		SpellBad = { sp = gui.red, undercurl = true },
		SpellCap = { sp = gui.yellow, undercurl = true },
		SpellLocal = { sp = gui.cyan, undercurl = true },
		SpellRare = { sp = gui.magenta, undercurl = true },
		Statement = { fg = gui.magenta, ctermfg = ansi.magenta, bold = true },
		StatusLine = {
			fg = gui.foreground,
			ctermfg = ansi.foreground,
			bg = gui.lighter_background,
			ctermbg = ansi.background,
		},
		StatusLineNC = {
			fg = gui.light_foreground,
			ctermfg = ansi.foreground,
			bg = gui.dark_background,
			ctermbg = ansi.background,
		},
		StorageClass = { fg = gui.yellow, ctermfg = ansi.yellow, bold = true },
		String = { fg = gui.green, ctermfg = ansi.green },
		Structure = { fg = gui.yellow, ctermfg = ansi.yellow, bold = true },
		Substitute = {
			fg = gui.background,
			ctermfg = ansi.background,
			bg = gui.magenta,
			ctermbg = ansi.magenta,
			bold = true,
		},
		TabLine = {
			fg = gui.light_foreground,
			ctermfg = ansi.foreground,
			bg = gui.dark_background,
			ctermbg = ansi.background,
		},
		TabLineFill = { bg = gui.dark_background, ctermbg = ansi.background },
		TabLineSel = {
			fg = gui.bright_foreground,
			ctermfg = ansi.bright_foreground,
			bg = gui.background,
			ctermbg = ansi.background,
			bold = true,
		},
		Tag = { fg = gui.blue, ctermfg = ansi.blue },
		TelescopeBorder = {
			fg = gui.muted,
			ctermfg = ansi.selection,
			bg = gui.lighter_background,
			ctermbg = ansi.background,
		},
		TelescopeMatching = { fg = gui.blue, ctermfg = ansi.blue, bold = true },
		TelescopeNormal = {
			fg = gui.foreground,
			ctermfg = ansi.foreground,
			bg = gui.lighter_background,
			ctermbg = ansi.background,
		},
		TelescopePromptBorder = {
			fg = gui.selection,
			ctermfg = ansi.selection,
			bg = gui.selection,
			ctermbg = ansi.selection,
		},
		TelescopePromptNormal = {
			fg = gui.foreground,
			ctermfg = ansi.foreground,
			bg = gui.selection,
			ctermbg = ansi.selection,
		},
		TelescopePromptPrefix = {
			fg = gui.accent,
			bg = gui.selection,
			ctermbg = ansi.selection,
		},
		TelescopePromptTitle = {
			fg = gui.background,
			ctermfg = ansi.background,
			bg = gui.accent,
			bold = true,
		},
		TelescopeResultsDiffAdd = { fg = gui.green, ctermfg = ansi.green },
		TelescopeResultsDiffChange = { fg = gui.yellow, ctermfg = ansi.yellow },
		TelescopeResultsDiffDelete = { fg = gui.red, ctermfg = ansi.red },
		TelescopeSelection = {
			fg = gui.bright_foreground,
			ctermfg = ansi.bright_foreground,
			bg = gui.selection,
			ctermbg = ansi.selection,
			bold = true,
		},
		TelescopeTitle = {
			fg = gui.accent,
			bg = gui.lighter_background,
			ctermbg = ansi.background,
			bold = true,
		},
		Title = { fg = gui.accent, bold = true },
		Todo = {
			fg = gui.background,
			ctermfg = ansi.background,
			bg = gui.yellow,
			ctermbg = ansi.yellow,
			bold = true,
		},
		Type = { fg = gui.yellow, ctermfg = ansi.yellow, bold = true },
		Typedef = { fg = gui.yellow, ctermfg = ansi.yellow, bold = true },
		Underlined = { fg = gui.blue, ctermfg = ansi.blue, underline = true },
		VertSplit = { fg = gui.muted, ctermfg = ansi.selection },
		Visual = { bg = gui.selection, ctermbg = ansi.selection },
		VisualNOS = { bg = gui.selection, ctermbg = ansi.selection },
		WarningMsg = { fg = gui.yellow, ctermfg = ansi.yellow, bold = true },
		WhichKey = { fg = gui.accent, bold = true },
		WhichKeyDesc = { fg = gui.foreground, ctermfg = ansi.foreground },
		WhichKeyFloat = { bg = gui.lighter_background, ctermbg = ansi.background },
		WhichKeyGroup = { fg = gui.cyan, ctermfg = ansi.cyan },
		WhichKeySeparator = { fg = gui.muted, ctermfg = ansi.selection },
		WhichKeyValue = { fg = gui.light_foreground, ctermfg = ansi.foreground, italic = true },
		Whitespace = { fg = gui.light_foreground, ctermfg = ansi.foreground },
		WildMenu = {
			fg = gui.bright_foreground,
			ctermfg = ansi.bright_foreground,
			bg = gui.selection,
			ctermbg = ansi.selection,
			bold = true,
		},
		WinBar = {
			fg = gui.foreground,
			ctermfg = ansi.foreground,
			bg = gui.background,
			ctermbg = ansi.background,
			bold = true,
		},
		WinBarNC = {
			fg = gui.light_foreground,
			ctermfg = ansi.foreground,
			bg = gui.background,
			ctermbg = ansi.background,
		},

		WinSeparator = { fg = gui.muted, ctermfg = ansi.selection },
		["@boolean"] = { link = "Boolean" },
		["@character"] = { link = "Character" },
		["@comment"] = { link = "Comment" },
		["@constant"] = { link = "Constant" },
		["@constant.builtin"] = { fg = gui.orange, ctermfg = ansi.yellow, italic = true },
		["@constructor"] = { fg = gui.yellow, ctermfg = ansi.yellow, bold = true },
		["@diff.delta"] = { fg = gui.yellow, ctermfg = ansi.yellow },
		["@diff.minus"] = { fg = gui.red, ctermfg = ansi.red },
		["@diff.plus"] = { fg = gui.green, ctermfg = ansi.green },
		["@field"] = { fg = gui.blue, ctermfg = ansi.blue },
		["@float"] = { link = "Float" },
		["@function"] = { link = "Function" },
		["@function.builtin"] = { fg = gui.cyan, ctermfg = ansi.cyan, bold = true },
		["@function.call"] = { fg = gui.blue, ctermfg = ansi.blue },
		["@function.method"] = { fg = gui.blue, ctermfg = ansi.blue, bold = true },
		["@function.method.call"] = { fg = gui.blue, ctermfg = ansi.blue },
		["@keyword"] = { link = "Keyword" },
		["@keyword.conditional"] = { fg = gui.magenta, ctermfg = ansi.magenta, bold = true },
		["@keyword.function"] = { fg = gui.magenta, ctermfg = ansi.magenta, bold = true },
		["@keyword.import"] = { fg = gui.cyan, ctermfg = ansi.cyan, bold = true },
		["@keyword.operator"] = { fg = gui.cyan, ctermfg = ansi.cyan, bold = true },
		["@keyword.repeat"] = { fg = gui.magenta, ctermfg = ansi.magenta, bold = true },
		["@keyword.return"] = { fg = gui.magenta, ctermfg = ansi.magenta, bold = true },
		["@markup.heading"] = { fg = gui.accent, bold = true },
		["@markup.italic"] = { fg = gui.foreground, ctermfg = ansi.foreground, italic = true },
		["@markup.link"] = { fg = gui.blue, ctermfg = ansi.blue, underline = true },
		["@markup.raw"] = { fg = gui.green, ctermfg = ansi.green },
		["@markup.strong"] = {
			fg = gui.bright_foreground,
			ctermfg = ansi.bright_foreground,
			bold = true,
		},
		["@number"] = { link = "Number" },
		["@operator"] = { link = "Operator" },
		["@property"] = { fg = gui.blue, ctermfg = ansi.blue },
		["@punctuation.bracket"] = { fg = gui.foreground, ctermfg = ansi.foreground },
		["@punctuation.delimiter"] = { fg = gui.muted, ctermfg = ansi.selection },
		["@punctuation.special"] = { fg = gui.cyan, ctermfg = ansi.cyan },
		["@string"] = { link = "String" },
		["@string.documentation"] = { fg = gui.green, ctermfg = ansi.green, italic = true },
		["@string.escape"] = { fg = gui.orange, ctermfg = ansi.yellow, bold = true },
		["@string.special"] = { fg = gui.cyan, ctermfg = ansi.cyan },
		["@tag"] = { fg = gui.blue, ctermfg = ansi.blue, bold = true },
		["@tag.attribute"] = { fg = gui.yellow, ctermfg = ansi.yellow },
		["@tag.delimiter"] = { fg = gui.muted, ctermfg = ansi.selection },
		["@type"] = { link = "Type" },
		["@type.builtin"] = { fg = gui.yellow, ctermfg = ansi.yellow, italic = true },
		["@type.definition"] = { fg = gui.yellow, ctermfg = ansi.yellow, bold = true },
		["@variable"] = { fg = gui.foreground, ctermfg = ansi.foreground },
		["@variable.builtin"] = { fg = gui.red, ctermfg = ansi.red, italic = true },
		["@variable.member"] = { fg = gui.blue, ctermfg = ansi.blue },
		["@variable.parameter"] = { fg = gui.foreground, ctermfg = ansi.foreground, italic = true },
		markdownBold = { fg = gui.bright_foreground, ctermfg = ansi.bright_foreground, bold = true },
		markdownCode = { fg = gui.green, ctermfg = ansi.green },
		markdownCodeBlock = { fg = gui.green, ctermfg = ansi.green },
		markdownH1 = { fg = gui.accent, bold = true },
		markdownH2 = { fg = gui.blue, ctermfg = ansi.blue, bold = true },
		markdownH3 = { fg = gui.cyan, ctermfg = ansi.cyan, bold = true },
		markdownH4 = { fg = gui.green, ctermfg = ansi.green, bold = true },
		markdownItalic = { fg = gui.foreground, ctermfg = ansi.foreground, italic = true },
		markdownLinkText = { fg = gui.blue, ctermfg = ansi.blue, underline = true },
	}

	return highlights
end

return M
